# Generated by Django 5.1.1 on 2024-10-13 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=50, unique=True)),
                ('discord_username', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('discriminator', models.CharField(max_length=4)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('discord_roles', models.ManyToManyField(blank=True, related_name='discord_roles', to='roles.discordrole')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
