# Generated by Django 5.1.1 on 2024-10-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='display_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
