name: nw-companion

services:
  django:
    container_name: django_nwcompanion
    build:
      context: ./django_api
      dockerfile: Dockerfile
    volumes:
      - ./django_api:/app
    command: sleep infinity
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - nwcompanion-network
      - vps-network
    environment:
      - DJANGO_POSTGRES_DB=${DJANGO_POSTGRES_DB}
      - DJANGO_POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - DJANGO_POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - DJANGO_POSTGRES_HOST=${DJANGO_POSTGRES_HOST}
      - DJANGO_POSTGRES_PORT=${DJANGO_POSTGRES_PORT}

  postgres:
    container_name: pg_nwcompanion
    image: postgres:13.16-bookworm
    restart: unless-stopped
    volumes:
      - nw-companion-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
    networks:
      - nwcompanion-network
      - vps-network

  discord_bot:
    container_name: discord_bot_nwcompanion
    build: ./discord_bot
    volumes:
      - ./discord_bot:/app
    command: python bot.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_PASSWORD=${BOT_PASSWORD}
    networks:
      - nwcompanion-network

networks:
  nwcompanion-network:
    driver: bridge
  vps-network:
    external: true

volumes:
  nw-companion-pgdata: {}
