name: nw-companion

services:
  django:
    container_name: django_api
    build:
      context: ./django_api
      dockerfile: Dockerfile
    volumes:
      - ./django_api:/workspaces/django_api
    command: sleep infinity
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    container_name: postgres
    image: postgres:13.16-bookworm
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
    ports:
      - "5431:5432"

  discord_bot:
    container_name: discord_bot
    build: ./discord_bot
    volumes:
      - ./discord_bot:/workspaces/discord_bot
    command: python bot.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_PASSWORD=${BOT_PASSWORD}
    depends_on:
      - db

  # front:
  #   build: .
  #   depends_on:
  #     - db
  #     - back
  
  proxy:
    contaner_name: nginx 
    image: nginx
    ports: 
      - "80:80"

  adminer:
    container_name: adminer 
    image: adminer
    # restart: always
    ports: 
      - 8081:8080

volumes:
  pgdata: {}
