name: 
  nw-companion

services:
  django:
    container_name: django-nw-companion
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces
    command: sleep infinity
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    container_name: pg-nw-companion
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
    ports:
      - "5431:5432"

  discord_bot:
    build: .
    volumes:
      - .:/workspaces
    command: python discord_bot/bot.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_PASSWORD=${BOT_PASSWORD}
    depends_on:
      - db

  # front:
  #   build: .
  #   depends_on:
  #     - db
  #     - back
  
  proxy:
    image: nginx
    ports: 
      - "80:80"

  adminer:
    image: adminer
    # restart: always
    ports: 
      - 8081:8080

volumes:
  pgdata: {}
