
services:
  django:
    container_name: django-nw-companion
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces
    command: sleep infinity
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    container_name: pg-nw-companion
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
volumes:
  pgdata: {}
