"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

import sys
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(BASE_DIR, 'discord'))
sys.path.append(os.path.join(BASE_DIR, 'new_world'))

# Initialiser le chargement de .env
load_dotenv()

# VARIABLES DISCORD 
DISCORD_CLIENT_ID = os.getenv('DISCORD_CLIENT_ID')
DISCORD_CLIENT_SECRET = os.getenv('DISCORD_CLIENT_SECRET')
DISCORD_REDIRECT_URI = os.getenv('DISCORD_REDIRECT_URI')
DISCORD_AUTH_URL = os.getenv('DISCORD_AUTH_URL')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECRET_KEY = os.getenv('SECRET_KEY')
# DEBUG = os.getenv('DEBUG', 'False') == True
# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost').split(',')

SECRET_KEY = 'django-insecure-z&rp*22j8ytmh1!^(id18dz7=-27@ilrz&%mb73=4bk12sp)$-'
DEBUG = True
# ALLOWED_HOSTS = ["localhost"]


# Application definition

HAS_MULTI_TYPE_TENANTS = True
MULTI_TYPE_DATABASE_FIELD = 'game_type'

TENANT_TYPES = {
    # TENANT PUBLIC 
    "public": {
        "APPS": [
            # Apps
            'django_tenants',
            'tenant_users.permissions',
            'tenant_users.tenants',

            'shared.users',
            'shared.tenants',
            'shared.new_world',

            # Django apps par défaut
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            
            # Apps partagées
            'rest_framework',
            'rest_framework_simplejwt',
            'corsheaders',
        ],
        "URLCONF": "core.urls",
    },

    # TENANT NEW_WORLD
    "new_world": {
        "APPS": [
            'django.contrib.contenttypes',
            'django.contrib.auth',
            'tenant_users.permissions',

            # 'shared.new_world',
            'games.discord.members',
            'games.discord.roles',
            'games.new_world.characters',
            'games.new_world.wars',

            'django.contrib.sessions',
            'django.contrib.messages',
        ],
        "URLCONF": "games.urls",
    },

    # TEMPLATE AUTRE TENANT
    # "nom_game_type": {
    #     "APPS": [
    #         'django.contrib.contenttypes',
    #         'django.contrib.auth',
    #         'tenant_users.permissions',

    #         # LISTE DES APPS DU JEU
    #         # ....

    #         'django.contrib.sessions',
    #         'django.contrib.messages',
    #     ],
    #     "URLCONF": "games.nom_game_type.urls"
    # },
}

INSTALLED_APPS = []

for schema in TENANT_TYPES:
    INSTALLED_APPS += [app for app in TENANT_TYPES[schema]["APPS"] if app not in INSTALLED_APPS]

ROOT_URLCONF = ''

TENANT_MODEL = 'tenants.Tenant'
TENANT_DOMAIN_MODEL = 'tenants.Domain'
PUBLIC_SCHEMA_NAME = 'public'

AUTHENTICATION_BACKENDS = ("tenant_users.permissions.backend.UserBackend",)
TENANT_USERS_DOMAIN = "localhost"
AUTH_USER_MODEL = "users.TenantUser"

# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenant_users.tenants.middleware.TenantAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'games.middleware.TenantSchemaMiddleware',
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.getenv('DJANGO_POSTGRES_DB'),
        'USER': os.getenv('DJANGO_POSTGRES_USER'),
        'PASSWORD': os.getenv('DJANGO_POSTGRES_PASSWORD'),
        'HOST': os.getenv('DJANGO_POSTGRES_HOST'),  
        'PORT': os.getenv('DJANGO_POSTGRES_PORT'),
    }
}

# The correct apps can be synced, depending on what's being synced (shared or tenant)

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
