# Generated by Django 5.1.1 on 2024-09-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_perk_rarity_delete_equipmentpiece_item_perks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='allowed_item_types',
            field=models.CharField(choices=[('headwear', 'Helmet'), ('chestwear', 'Chest'), ('glove', 'Gloves'), ('legwaer', 'Legs'), ('footwear', 'Boots'), ('ring', 'Rings'), ('earswear', 'Ears'), ('necklace', 'Necklace'), ('primary_weapon', 'Primary Weapon'), ('secondary_weapon', 'Secondary Weapon')], max_length=100),
        ),
    ]
