# Generated by Django 5.1.1 on 2024-09-26 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_game_username_character_pseudo_in_game_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_characters', to='members.characterrole'),
        ),
        migrations.AlterField(
            model_name='characterrole',
            name='role',
            field=models.ForeignKey(limit_choices_to={'type': 'game'}, on_delete=django.db.models.deletion.CASCADE, to='members.role'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
