# Generated by Django 5.1.1 on 2024-09-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_characterrole_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterrole',
            old_name='role',
            new_name='classe',
        ),
    ]
